### ISSUE TITLE
Baseline implementations are missing or incorrect.

### ISSUE THREAD

**Issue by PanYicheng** [tsinghua-fib-lab/Traffic-Benchmark#6]
Thanks for the code of the DGCRN.

From the description and the repo title, I assume there should be baseline methods such as LSTM and FNN. However, in their sub-directories under 'methods', the models are all STMetaNet. This maybe due to your carelessness. As I also want to compare with those baseline methods,  I hope that you can provide those implementations. 

Thank you after all.

This is two files of FNN and STMetaNet. Yet the code is the same.
![Screenshot 2021-09-28 161549](https://user-images.githubusercontent.com/25337258/135049862-a8cf1800-3d9d-4d6a-8bb7-f5d2409221f5.jpg)

**Comment by LiFXe** [comment]
Although the file names are the same, the codes are different. Please refer to: https://github.com/tsinghua-fib-lab/Traffic-Benchmark/blob/b9f8e40b4df9b58f5ad88432dc070cbbbcdc0228/methods/FNN/model/pytorch/dcrnn_model.py#L697

**Comment by PanYicheng** [comment]
Oh, I see. Thanks for reminding me.
